-- Reusable suggested queries (generated by LLM)

-- id: 7c97ed2cc0725ecc424508ee621db958c6d533a5c061ca088e632e989b6e2ef6
-- summary: Consider using a JOIN instead of a subquery for better performance.
SELECT u.id, u.name, COUNT(o.id) AS completed_orders FROM users u LEFT JOIN orders o ON o.user_id = u.id AND o.status = 'completed' WHERE u.signup_date > '2025-01-01' GROUP BY u.id, u.name

